# Generated by Django 4.2.1 on 2023-05-30 21:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_Cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='IdCliente')),
                ('Nombre_Cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Cliente')),
                ('Email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de contacto')),
                ('Identificacion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Identificación ')),
                ('Tipo_Identificacion', models.CharField(choices=[('CEDULA', 'CEDULA'), ('RUC', 'RUC'), ('PASAPORTE', 'PASAPORTE')], max_length=15, verbose_name='Tipo de Identificación')),
            ],
        ),
        migrations.CreateModel(
            name='MaestroTiposServicios',
            fields=[
                ('Id_MTipoServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='IdMTipoServicios')),
                ('Nombre_Tipo_Servicio', models.CharField(max_length=250, verbose_name='Tipo de servicio')),
                ('Estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15, verbose_name='Estado del Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('Id_Vehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='IdVehiculo')),
                ('Marca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca')),
                ('Modelo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modelo')),
                ('Placa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa')),
                ('Nivel_Combustible', models.CharField(choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('FULL', 'FULL')], max_length=15, verbose_name='Nivel de Combustible')),
                ('Detalles_vehiculo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detalles del Vehiculo')),
                ('Id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente', to='car.clientes', verbose_name='Id del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('Id_Servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='IdServicio')),
                ('Fecha_Inicio_Trabajo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio de trabajo')),
                ('Fecha_Fin_Trabajo', models.DateTimeField(verbose_name='Fecha de Fin de trabajo')),
                ('Estado_Servicio', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('TERMINADO', 'TERMINADO')], default='PENDIENTE', max_length=50, verbose_name='Estado de Servicio')),
                ('Id_Vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Vehiculo', to='car.vehiculos', verbose_name='Id del Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='MaestroServicios',
            fields=[
                ('Id_MServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='IdMServicios')),
                ('Nombre_Servicio', models.CharField(max_length=250, verbose_name='Nombre del servicio')),
                ('Estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15, verbose_name='Estado del Servicio')),
                ('Precio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio del Servicio')),
                ('Id_MTipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TipodeServicio', to='car.maestrotiposservicios', verbose_name='Id del Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linea_Detalle', models.IntegerField(verbose_name='Linea de detalle')),
                ('Nombre_Servicio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Servicio')),
                ('Id_Servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Servicio', to='car.servicios', verbose_name='Id del Servicio')),
            ],
        ),
    ]
